AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NestJS + Express on Lambda with HTTP API(v2) & CORS

Parameters:
  AllowedOrigin:
    Type: String
    Default: https://codingbyohj.com
  SmtpHost:
    Type: String
    Default: smtp.gmail.com
  SmtpPort:
    Type: Number
    Default: 587
  SmtpUser:
    Type: String
    NoEcho: true
  SmtpPass:
    Type: String
    NoEcho: true
  EmailFrom:
    Type: String
  EmailTo:
    Type: String

Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Resources:
  # 문의 API에서 필요한 출처와 메서드만 허용합니다.
  MyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyProfileRestApi
      StageName: prod
      Cors:
        AllowOrigin: !Sub "'${AllowedOrigin}'"
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type'"
        MaxAge: 600

  # 2) Lambda 함수
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-profile-api
      CodeUri: dist/
      Handler: lambda.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          ALLOWED_ORIGIN: !Ref AllowedOrigin
          SMTP_HOST: !Ref SmtpHost
          SMTP_PORT: !Ref SmtpPort
          SMTP_USER: !Ref SmtpUser
          SMTP_PASS: !Ref SmtpPass
          EMAIL_FROM: !Ref EmailFrom
          EMAIL_TO: !Ref EmailTo
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi    # 반드시 CORS 연 MyHttpApi를 참조
            Path: /{proxy+}      # /api/* 전부를 처리
            Method: ANY

Outputs:
  RestApiInvokeUrl:
    Description: "Invoke URL for REST API"
    Value: !Sub "https://${MyRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
