# back/template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NestJS Lambda via SAM

Globals:
  Function:
    # 람다에 공통 적용할 설정 (타임아웃, 메모리 등)
    Timeout: 10
    MemorySize: 256

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-profile-api
      # 빌드된 JS가 들어있는 폴더
      CodeUri: dist/
      Handler: lambda.handler
      Runtime: nodejs18.x
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SMTP_HOST:   "smtp.gmail.com"
          SMTP_PORT:   "587"
          SMTP_USER:   "ddaaadd01@gmail.com"
          SMTP_PASS:   "cccg oert paam gych"
          EMAIL_FROM:  "Hyunji Oh <ddaaadd01@gmail.com>"
          EMAIL_TO:    "ddaaadd01@gmail.com"
