# back/template.yaml
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-profile-api
      CodeUri: dist/
      Handler: src/main.lambda.handler
      Runtime: nodejs18.x
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SMTP_HOST:   "smtp.gmail.com"
          SMTP_PORT:   "587"
          SMTP_USER:   "ddaaadd01@gmail.com"
          SMTP_PASS:   "cccg oert paam gych"
          EMAIL_FROM:  "Hyunji Oh <ddaaadd01@gmail.com>"
          EMAIL_TO:    "ddaaadd01@gmail.com"
