AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NestJS + Express on Lambda with HTTP API(v2) & CORS

Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Resources:
  # 1) HTTP API(v2) 정의 & CORS 열기
  MyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyProfileRestApi
      StageName: prod
      Cors:
        AllowOrigins: "'*'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE,PATCH'"
        AllowHeaders: "'Content-Type,Authorization'"
        MaxAge: 600

  # 2) Lambda 함수
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-profile-api
      CodeUri: dist/
      Handler: lambda.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          SMTP_HOST:   "smtp.gmail.com"
          SMTP_PORT:   "587"
          SMTP_USER:   "ddaaadd01@gmail.com"
          SMTP_PASS:   "cccg oert paam gych"
          EMAIL_FROM:  "Hyunji Oh <ddaaadd01@gmail.com>"
          EMAIL_TO:    "ddaaadd01@gmail.com"
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi    # 반드시 CORS 연 MyHttpApi를 참조
            Path: /{proxy+}      # /api/* 전부를 처리
            Method: ANY

Outputs:
  HttpApiUrl:
    Description: "Invoke URL for HTTP API"
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

         