# .github/workflows/deploy.yml
name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy-web:
    name: "→ Frontend: Next.js → S3 + CloudFront"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies (web)
        working-directory: front
        run: npm ci

      - name: Build (web)
        working-directory: front
        run: npm run build
        

      - name: Sync to S3
        env:
          BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        run: aws s3 sync front/out/ s3://$BUCKET --delete

      - name: Invalidate CloudFront
        env:
          DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"

  deploy-api:
    name: "→ Backend: NestJS → Lambda (SAM)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies (api)
        working-directory: back
        run: npm ci

      - name: Build (api)
        working-directory: back
        run: |
          # 1) Nest 컴파일
          npm ci
          npm run build
          # 2) production 의존성 복사
          npm prune --production
          cp -R node_modules dist/

      - name: Package for SAM
        working-directory: back
        run: |
          sam package \
            --template-file template.yaml \
            --s3-bucket ${{ secrets.SAM_ARTIFACTS_BUCKET }} \
            --output-template-file packaged.yaml


      - name: Deploy with SAM
        working-directory: back
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name ${{ secrets.STACK_NAME }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \ 
            --capabilities CAPABILITY_IAM
